create table if not exists public.inforu_logs (
  id bigint generated by default as identity primary key,
  did text not null,
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default timezone('asia/jerusalem', now())
);

create index if not exists inforu_logs_sent_at_idx
  on public.inforu_logs(sent_at desc);

create index if not exists inforu_logs_did_idx
  on public.inforu_logs(did);

create unique index if not exists inforu_logs_did_sent_at_uidx
  on public.inforu_logs(did, sent_at);
