create table if not exists public.ticket_boards (
  slug text primary key,
  name text not null,
  icon_path text not null default '',
  route_path text not null,
  sort_order integer not null default 1,
  created_at timestamptz not null default timezone('asia/jerusalem', now())
);

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  board_slug text not null references public.ticket_boards(slug) on delete restrict,
  created_at timestamptz not null,
  created_at_display text not null,
  creator text not null,
  ticket_type text not null default '',
  service_type text not null default '',
  domain text not null default '',
  priority text not null default 'Medium',
  description text not null default '',
  solution text not null default '',
  status text not null default 'Waiting',
  assigned_to text not null default '',
  details jsonb not null default '{}'::jsonb
);

create table if not exists public.ticket_updates (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  changed_at timestamptz not null,
  actor text not null,
  field_name text not null,
  old_value text not null default '',
  new_value text not null default ''
);

create table if not exists public.ticket_attachments (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  original_name text not null,
  saved_name text not null,
  folder text not null,
  url text not null,
  created_at timestamptz not null default timezone('asia/jerusalem', now())
);

create table if not exists public.support_app_users (
  email text primary key,
  password_hash text not null,
  role text not null default 'user',
  allowed_pages jsonb not null default '["home","sms","bot","f2m","recording_storage","human_service","record","features_report","support_tickets","pais_tickets","nastia_tickets"]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default timezone('asia/jerusalem', now())
);

create index if not exists support_tickets_board_slug_idx on public.support_tickets(board_slug);
create index if not exists support_tickets_status_idx on public.support_tickets(status);
create index if not exists support_tickets_assigned_to_idx on public.support_tickets(assigned_to);
create index if not exists ticket_updates_ticket_id_idx on public.ticket_updates(ticket_id);
create index if not exists ticket_attachments_ticket_id_idx on public.ticket_attachments(ticket_id);
create index if not exists support_app_users_active_idx on public.support_app_users(active);

insert into public.ticket_boards (slug, name, icon_path, route_path, sort_order)
values
  ('support', 'Support Tickets', '', '/support-tickets', 1),
  ('pais', 'מפעל הפיס', '/picture/pais.png', '/pais-tickets', 2)
on conflict (slug) do update
set
  name = excluded.name,
  icon_path = excluded.icon_path,
  route_path = excluded.route_path,
  sort_order = excluded.sort_order;

insert into public.support_app_users (email, password_hash, role, allowed_pages, active)
values (
  'nastya@nimbusip.com',
  'scrypt:32768:8:1$53nNPimyycdSlojs$076085ce5b96ec5783150231fd74b66b213986b05bf9507ac2b6219b0c10a969efd0ac6f99c32223cf997dc8500a2345b5502e22c676dac29958ca5a40ceeb95',
  'tickets_only',
  '["support_tickets","pais_tickets"]'::jsonb,
  true
)
on conflict (email) do update
set
  password_hash = excluded.password_hash,
  role = excluded.role,
  allowed_pages = excluded.allowed_pages,
  active = excluded.active;
